name: ci
on:
  push:
    branches:
      - main
  pull_request: ~

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.15.1
          # CLI arguments
          args: --color always --check .
  unit_tests:
    name: unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/v0.9.0/nvim-linux64.tar.gz
            version: 0.9.0
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/v0.10.0/nvim-linux64.tar.gz
            version: 0.10.0
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-linux-x86_64.tar.gz
            version: 0.11.0
          - os: ubuntu-latest
            url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
            version: nightly

    steps:
      - uses: actions/checkout@v4
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v4
        with:
          path: _neovim
          key: ${{ runner.os }}-x64-${{ hashFiles('todays-date') }}-${{ matrix.version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install npm packages
        run: |
          cd ./spec
          npm ci
          cd ..
      - name: Install neotest-jest dependencies
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL ${{ matrix.url }} | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-neotest/neotest.git ~/.local/share/nvim/site/pack/vendor/start/neotest
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter.git ~/.local/share/nvim/site/pack/vendor/start/nvim-treesitter
          git clone --depth 1 https://github.com/nvim-neotest/nvim-nio ~/.local/share/nvim/site/pack/vendor/start/nvim-nio
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --headless -c 'TSInstall javascript typescript | quit'
      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          ./scripts/test
      - name: Dump neotest log
        if: '!cancelled()'
        run: cat ~/.local/state/nvim/neotest.log
